### ISSUE TITLE
Error: Cannot read property of 'session' undefined

### ISSUE THREAD

**Issue by moderniseobservatory** [givo/kurento-rtpendpoint#5]
I tried running the this src code changing only the IP address for the media server/ websocket. 
I works if i run it on my local host (but that is not where the media server is hosted). But i try running it on the same server as is hosting KMS then i get the above error from line 180: index.js

` return function session(req, res, next) {
    // self-awareness
    if (req.session) {   // LINE 180
      next()
      return
    }
`

Any suggestions on how to solve this?

**Comment by givo** [comment]
hi,

Please add a snippet of your exact changes because it is not clear which line and in which file the exception is thrown.

In addition, please give me more details of the exception code and description.

**Comment by moderniseobservatory** [comment]
I pushed all changes I made in the latest commit to [https://github.com/Squrrli/kurento-rtpendpoint/commits/master](url) which i forked from your repo. The only changes were to the url that the kms is being hosted on and adding a 'new' keyword when creating the 
`var wss` as it was giving the following error:

```
adam@nodered:~/rtpend$ node server.js
/home/adam/rtpend/server.js:35
var wss =  ws.Server({
              ^

TypeError: Class constructor WebSocketServer cannot be invoked without 'new'
    at Object.<anonymous> (/home/adam/rtpend/server.js:35:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
```



The error that i am receiving is:

```
adam@nodered:~/rtpend$ node server.js
listenning at 3000
/home/adam/rtpend/node_modules/express-session/index.js:180
    if (req.session) {
            ^

TypeError: Cannot read property 'session' of undefined
    at session (/home/adam/rtpend/node_modules/express-session/index.js:180:13)
    at WebSocketServer.connect (/home/adam/rtpend/server.js:47:5)
    at WebSocketServer.emit (events.js:182:13)
    at WebSocketServer.EventEmitter.emit (domain.js:442:20)
    at handleUpgrade (/home/adam/rtpend/node_modules/ws/lib/websocket-server.js:82:18)
    at WebSocketServer.completeUpgrade (/home/adam/rtpend/node_modules/ws/lib/websocket-server.js:294:5)
    at WebSocketServer.handleUpgrade (/home/adam/rtpend/node_modules/ws/lib/websocket-server.js:233:10)
    at Server.upgrade (/home/adam/rtpend/node_modules/ws/lib/websocket-server.js:81:16)

    at Server.emit (events.js:182:13)
    at Server.EventEmitter.emit (domain.js:442:20)
```

**Comment by moderniseobservatory** [comment]
The server that is hosting the node server and KMS is running Ubuntu 16.04 xenial and has node v10.6.0 installed on it along with latest versions of any node_modules that are required through `npm install`

**Comment by givo** [comment]
I have created this example a long time ago, I don't recommend you to use this code in production.

It uses the `async` package instead of using a much prettier concept like `async-await`.

Have a look at [lib-kurento](https://github.com/givo/lib-kurento) package which I have uploaded, it suppose to make your life much easier.

Pay attention, it is written in Typescript.
